"""Initial Migration

Revision ID: 02833290efd6
Revises: 
Create Date: 2025-07-15 11:15:00.685948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02833290efd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notification_related_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['related_post_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_related_post_id_fkey'), 'post', ['related_post_id'], ['id'])

    # ### end Alembic commands ###
