"""Column name change is_visible  Visibility for Soft Deletion

Revision ID: 0c8950fdded4
Revises: fc2c239a4cee
Create Date: 2025-07-15 15:17:57.794829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8950fdded4'
down_revision = 'fc2c239a4cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
