"""Added tip model

Revision ID: f066a039b897
Revises: 0c8950fdded4
Create Date: 2025-07-16 12:35:20.050720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f066a039b897'
down_revision = '0c8950fdded4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tip')
    # ### end Alembic commands ###
