"""Added Post Visibility for Soft Deletion

Revision ID: fc2c239a4cee
Revises: 02833290efd6
Create Date: 2025-07-15 15:15:24.072448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2c239a4cee'
down_revision = '02833290efd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
